# Generated by Django 3.2 on 2021-04-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('productid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=4000)),
                ('technical_specs', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
