# Generated by Django 3.2 on 2021-04-27 05:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=4000)),
                ('phone_number', models.CharField(max_length=12)),
                ('social_media_links', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime(2021, 4, 27, 1, 53, 35, 778368))),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime(2021, 4, 27, 1, 53, 35, 778368))),
                ('list_of_products', models.CharField(max_length=200)),
                ('amount_payed', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
